### ISSUE TITLE
Don't caching dist

### ISSUE THREAD

**Issue by AlexPitTech** [isaaceindhoven/composer-velocita#6]
Hello!
I'm trying to use this docker image, but i can't seem to get it to store package dist cache 

```
  velocita:
    container_name: velocita
    image: isaaceindhoven/velocita-proxy
    volumes:
      - ./.cyberplace/velocita:/var/cache/velocita
    restart: always
    environment:
      MIRROR_PACKAGIST_URL: https://repo.packagist.org
      MIRROR_PACKAGIST_TYPE: composer
      MIRROR_ASSET_PACKAGIST_URL: https://asset-packagist.org
      MIRROR_ASSET_PACKAGIST_TYPE: composer
      MIRROR_GITHUB_URL: https://api.github.com
      #MIRROR_GITHUB_TYPE: composer
      #MIRROR_GITHUB_TYPE: git
      MIRROR_GITHUB_TYPE: zip
      VIRTUAL_HOST: velocita.tech
      VIRTUAL_PORT: 8080
      VELOCITA_URL: http://localhost:8080
      VELOCITA_HTTP_PORT: 8080
      VELOCITA_HTTPS_PORT: 8443
```

Also I added target link in my composer.lock

```
            "dist": {
                "type": "zip",
                "url": "http://velocita:8080/mirror/github/repos/doctrine/cache/zipball/382e7f4db9a12dc6c19431743a2b096041bcdd62",
                "reference": "382e7f4db9a12dc6c19431743a2b096041bcdd62",
                "shasum": ""
            },
```

So I can download this zip by url, but don't cache it. Only http responses cached 

How it's work ?
